name: "Audit Dependencies"

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: The GITHUB_TOKEN
        required: true

permissions: read-all

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/audit@v1.1.5
