name: "Audit Dependencies"

on:
  workflow_call:

permissions:
  id-token: write
  issues: write
  security-events: write
  actions: read
  checks: read
  contents: read
  deployments: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/audit@v1.2.1
